### ISSUE TITLE
Jeepney blocking I/O back-end blocks indefinitely in `listen()`

### ISSUE THREAD

**Issue by nojocodex** [FFY00/dbus-objects#22]
The `dbus_objects.integration.jeepney.BlockingDBusServer` class `listen()` method calls `self._conn.receive()` without a timeout, which blocks indefinitely. I suppose that fits with blocking part in its name: `BlockingDBusServer` :-) But the method does take `delay` and `event` arguments, which makes me think it's intended to allow some external control of when it stops.

Such control would be helpful for e.g. being able to run a `BlockingDBusServer` in its own thread while allowing the main thread control over stopping it.

**Comment by FFY00** [comment]
Right, currently when the event is set we will only stop after the next message.
